generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true

    config:
      fields:
        username:       { label: Логин }
        password:       { label: Пароль }
        first_name:     { label: Имя }
        last_name:      { label: Фамилия }
        balance:        { label: Баланс }
        is_active:      { label: Статус }
        api_key:        { label: API KEY }
        password_again: { label: "Пароль (снова)" }
        last_login:     { label: Вход }
        email_address:  { label: email }
        link_to_activate: { label: Статус }
        personal_price: { label: Персональная цена }
        is_super_admin: { label: Администратор }
      list:
        title:   Аккаунты <a href="#" onclick="jQuery('#sf_admin_bar').slideToggle('slow')">(поиск)</a>
        display: [id, =username, first_name, last_name, email_address, _balance, _link_to_activate, created_at, last_login]
      filter:
        display: [username, email_address, first_name, last_name, is_active]
      form:
        class: sfGuardUserAdminForm
        display:
          "Аккаунт":                [username, password, password_again, personal_price]
          "Профиль":                [first_name, last_name, email_address, api_key]
          "Права и группы":         [is_active, is_super_admin]
      edit:
        title: Редактирование аккаунта "%%username%%"
      new:
        title: Новый аккаунт