generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true

    config:
      fields:
        id:             { label: № }
        username:       { label: Логин }
        user:           { label: Пользователь }
        password:       { label: Пароль }
        first_name:     { label: Имя }
        last_name:      { label: Фамилия }
        balance:        { label: Баланс }
        is_active:      { label: Активен }
        api_key:        { label: API KEY }
        password_again: { label: "Пароль (снова)" }
        last_login:     { label: Вход, date_format: 'dd.MM.yy HH:mm' }
        created_at:     { label: Регистрация, date_format: 'dd.MM.yy HH:mm' }
        email_address:  { label: E-mail }
        link_to_activate: { label: Статус }
        reward_balance: { label: Партнерский баланс }
        reward_size:    { label: Размер вознаграждения }
        phone:          { label: Мобильный }
        phone_is_confirmed: { label: Мобильный подтвержден }
        api_save_sender: { label: Сохранять имя отправителя }
        api_save_contacts: { label: Сохранять номера }
        api_tag_id:     { label: Применять тег }
        notify_email_enabled: { label: На email }
        notify_phone_enabled: { label: На мобильный }
        notify_balance_enabled: { label: При низком балансе }
        notify_payment_enabled: { label: При оплате счета }
        notify_balance_value: { label: Порог баланса }
        personal_price: { label: Персональная цена }
        is_super_admin: { label: Администратор }
      list:
        title:   Пользователи | <a href="#" onclick="jQuery('#sf_admin_bar').slideToggle('fast')">фильтр &darr;</a>
        display: [id, _user, email_address, _balance, _link_to_activate, created_at]
        object_actions:
          _edit: ~
      filter:
        display: [username, email_address, first_name, last_name, is_active, referer_id]
      form:
        class: sfGuardUserAdminForm
        display:
          "Аккаунт":                [username, password, password_again]
          "Партнеские":             [reward_balance, reward_size]
          "Профиль":                [first_name, last_name, email_address, phone, phone_is_confirmed]
          "API":                    [api_key, api_save_sender, api_save_contacts, api_tag_id]
          "Уведомления":            [notify_email_enabled, notify_phone_enabled, notify_payment_enabled, notify_balance_enabled, notify_balance_value]
          "Права и группы":         [is_active, is_super_admin]
      edit:
        title: Редактирование аккаунта "%%username%%"
      new:
        title: Новый аккаунт